version: "3.5"
services:
  api:
    build: ./app
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      NODE_HOST: ${NODE_HOST}
    volumes:
      - ./app:/usr/src/app
        
  db:
    image: postgres:11
    build: ./database
    container_name: pgsql
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - ./database/1.setup.sql:/docker-entrypoint-initdb.d/1.setup.sql
      
      # Uncomment if you want to add fixtures to the database
      - ./database/2.fixtures.sql:/docker-entrypoint-initdb.d/2.fixtures.sql
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped      


networks:
  postgres:
    driver: bridge      